# Generated by Django 4.2 on 2024-12-29 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_category_trasaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trasaction",
            options={"ordering": ["-date"]},
        ),
    ]
