# Generated by Django 4.2 on 2024-12-29 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_trasaction_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Trasaction",
            new_name="Transaction",
        ),
    ]
